language: go
go:
  - 1.x
addons:
  ssh_known_hosts: eyskens.me
  apt:
    packages:
        - sshpass
        - wget 
sudo: required

install:
  - export SSHPASS=$DEPLOY_PASS
  - wget -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
  - hugo

after_success:
- sshpass -e rsync -avz --delete public/ blog@eyskens.me:/var/www/blog/